# Generated by Django 3.2.9 on 2022-01-07 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.CharField(max_length=50, verbose_name='Corretor')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=50, verbose_name='CPF')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('income', models.CharField(choices=[('Formal', 'Formal'), ('Informal', 'Informal'), ('Mista', 'Mista')], max_length=50, verbose_name='Renda')),
                ('marital_status', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Separado(a)', 'Separado(a)'), ('Divorciado(a)', 'Divorciado(a)')], max_length=50, verbose_name='Estado Civil')),
                ('cpf_spouse', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF do cônjuge')),
                ('broker', models.CharField(max_length=50, verbose_name='Telefone do corretor')),
                ('real_estate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Imobiliária')),
                ('agency', models.CharField(max_length=50, verbose_name='Agência')),
                ('service', models.CharField(choices=[('Habitacional', 'Habitacional'), ('Comercial', 'Comercial')], max_length=50, verbose_name='Tipo de serviço')),
                ('enterprise', models.CharField(blank=True, max_length=50, null=True, verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUsers',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('employees', models.CharField(max_length=50, verbose_name='Corretor')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=50, verbose_name='CPF')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('income', models.CharField(choices=[('Formal', 'Formal'), ('Informal', 'Informal'), ('Mista', 'Mista')], max_length=50, verbose_name='Renda')),
                ('marital_status', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Separado(a)', 'Separado(a)'), ('Divorciado(a)', 'Divorciado(a)')], max_length=50, verbose_name='Estado Civil')),
                ('cpf_spouse', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF do cônjuge')),
                ('broker', models.CharField(max_length=50, verbose_name='Telefone do corretor')),
                ('real_estate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Imobiliária')),
                ('agency', models.CharField(max_length=50, verbose_name='Agência')),
                ('service', models.CharField(choices=[('Habitacional', 'Habitacional'), ('Comercial', 'Comercial')], max_length=50, verbose_name='Tipo de serviço')),
                ('enterprise', models.CharField(blank=True, max_length=50, null=True, verbose_name='Empreendimento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Documentos')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_user', to='users.users')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
