# Generated by Django 3.2.9 on 2021-11-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='income',
            field=models.CharField(choices=[('Formal', 'Formal'), ('Informal', 'Informal'), ('Mista', 'Mista')], max_length=50, verbose_name='Renda'),
        ),
        migrations.AlterField(
            model_name='users',
            name='marital_status',
            field=models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Separado(a)', 'Separado(a)'), ('Divorciado(a)', 'Divorciado(a)')], max_length=50, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='users',
            name='service',
            field=models.CharField(choices=[('Habitacional', 'Habitacional'), ('Comercial', 'Comercial')], max_length=50, verbose_name='Renda'),
        ),
    ]
