# Generated by Django 3.2.9 on 2021-11-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='employees',
            field=models.CharField(max_length=50, verbose_name='Corretor'),
        ),
        migrations.AlterField(
            model_name='users',
            name='service',
            field=models.CharField(choices=[('Habitacional', 'Habitacional'), ('Comercial', 'Comercial')], max_length=50, verbose_name='Tipo de serviço'),
        ),
    ]
