# Generated by Django 3.2.9 on 2021-11-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
