# Generated by Django 3.2.9 on 2021-11-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'Em análise'), (1, 'Assinar formulários'), (2, 'Aprovado Habitacional')], max_length=50, verbose_name='Status')),
                ('valor_financiamento', models.CharField(max_length=50, verbose_name='Valor financiamento')),
            ],
        ),
    ]
