# Generated by Django 3.2.9 on 2021-11-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.RemoveField(
            model_name='status',
            name='valor_financiamento',
        ),
        migrations.AddField(
            model_name='status',
            name='informacoes',
            field=models.CharField(default='', max_length=250, verbose_name='Informações adcionais referente ao status'),
        ),
    ]
