# Generated by Django 3.2.9 on 2022-01-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20220111_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatus',
            name='information',
            field=models.TextField(blank=True, max_length=280, null=True, verbose_name='Informações'),
        ),
        migrations.AddField(
            model_name='status',
            name='information',
            field=models.TextField(blank=True, max_length=280, null=True, verbose_name='Informações'),
        ),
    ]
