# Generated by Django 3.2.9 on 2021-11-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('status', '0002_auto_20211116_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
