# Generated by Django 3.2.9 on 2021-11-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_status_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Em análise', 'Em análise'), ('Assinar formulários', 'Assinar formulários'), ('Aprovado Habitacional', 'Aprovado Habitacional'), ('Aprovado Comercial', 'Aprovado Comercial'), ('Baixa FGTS', 'Baixa FGTS'), ('Enviado CEHOP', 'Enviado CEHOP'), ('Conforme', 'Conforme'), ('Vistoria', 'Vistoria'), ('Contrato Assinado', 'Contrato Assinado'), ('Registrado', 'Registrado'), ('QV Solicitado', 'QV Solicitado'), ('Restrição', 'Restrição'), ('Pendente Documento', 'Pendente Documento'), ('Inconforme', 'Inconforme'), ('Reprovado', 'Reprovado'), ('Internalizado', 'Internalizado'), ('Pendente Crítica', 'Pendente Crítica'), ('Garantia Análise CEHOP', 'Garantia Análise CEHOP'), ('Garantia Inconforme', 'Garantia Inconforme'), ('Garantia Conforme', 'Garantia Conforme'), ('Reavaliar', 'Reavaliar')], max_length=50, verbose_name='Status'),
        ),
    ]
