# Generated by Django 3.2.9 on 2021-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='informacoes',
            field=models.TextField(default='', max_length=250, verbose_name='Informações adcionais referente ao status'),
        ),
    ]
