# Generated by Django 3.2.9 on 2022-01-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20220118_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstatus',
            name='status',
            field=models.CharField(choices=[('Aprovado Comercial', 'Aprovado Comercial'), ('Aprovado Habitacional', 'Aprovado Habitacional'), ('Assinar Formularios', 'Assinar Formulários'), ('Baixa FGTS', 'Baixa FGTS'), ('Conforme', 'Conforme'), ('Contrato Assinado', 'Contrato Assinado'), ('Desistiu', 'Desistiu'), ('Em Analise', 'Em Análise'), ('Enviado CEHOP', 'Enviado CEHOP'), ('Garantia Analise CEHOP', 'Garantia Análise CEHOP'), ('Garantia Conforme', 'Garantia Conforme'), ('Garantia Inconforme', 'Garantia Inconforme'), ('Inconforme', 'Inconforme'), ('Internalizado', 'Internalizado'), ('Pendente Critica', 'Pendente Crítica'), ('Pendente Documento', 'Pendente Documento'), ('QV Solicitado', 'QV Solicitado'), ('Reavaliar', 'Reavaliar'), ('Registrado', 'Registrado'), ('Reprovado', 'Reprovado'), ('Restricao', 'Restrição'), ('Vistoria', 'Vistoria')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Aprovado Comercial', 'Aprovado Comercial'), ('Aprovado Habitacional', 'Aprovado Habitacional'), ('Assinar Formularios', 'Assinar Formulários'), ('Baixa FGTS', 'Baixa FGTS'), ('Conforme', 'Conforme'), ('Contrato Assinado', 'Contrato Assinado'), ('Desistiu', 'Desistiu'), ('Em Analise', 'Em Análise'), ('Enviado CEHOP', 'Enviado CEHOP'), ('Garantia Analise CEHOP', 'Garantia Análise CEHOP'), ('Garantia Conforme', 'Garantia Conforme'), ('Garantia Inconforme', 'Garantia Inconforme'), ('Inconforme', 'Inconforme'), ('Internalizado', 'Internalizado'), ('Pendente Critica', 'Pendente Crítica'), ('Pendente Documento', 'Pendente Documento'), ('QV Solicitado', 'QV Solicitado'), ('Reavaliar', 'Reavaliar'), ('Registrado', 'Registrado'), ('Reprovado', 'Reprovado'), ('Restricao', 'Restrição'), ('Vistoria', 'Vistoria')], max_length=50, verbose_name='Status'),
        ),
    ]
