# Generated by Django 3.2.9 on 2021-11-16 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_alter_status_informacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da última atualização'),
        ),
    ]
