# Generated by Django 3.2.9 on 2021-11-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_status_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='informacoes',
            field=models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='Informações adcionais referente ao status'),
        ),
    ]
